/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica2;

import javax.swing.JOptionPane;

/**
 *
 * @author pc1
 */
public class InterfazEliminarPersonaje extends javax.swing.JFrame {
    public int i ;
    public int posicion ;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazEliminarPersonaje.class.getName());

    private InterfazMenu im ;
    
    
    /**
     * Creates new form InterfazEliminarPersonaje
     */
    public InterfazEliminarPersonaje() {
        initComponents();
    }
    
    public void setIm(InterfazMenu im3){
        this.im = im3 ;
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancelarEliminarP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEliminarPorID = new javax.swing.JTextField();
        txtEliminarPorNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultadoBEliminar = new javax.swing.JTextArea();
        btnBuscarIdEliminar = new javax.swing.JButton();
        btnBuscarNombreEliminar = new javax.swing.JButton();
        btnConfirmarEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("    ELIMINAR PERSONAJE");

        btnCancelarEliminarP.setText("Cancelar");
        btnCancelarEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEliminarPActionPerformed(evt);
            }
        });

        jLabel2.setText("            Bucar por ID");

        jLabel3.setText("    Buscar por nombre");

        txtResultadoBEliminar.setColumns(20);
        txtResultadoBEliminar.setRows(5);
        jScrollPane1.setViewportView(txtResultadoBEliminar);

        btnBuscarIdEliminar.setText("Buscar");
        btnBuscarIdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdEliminarActionPerformed(evt);
            }
        });

        btnBuscarNombreEliminar.setText("Buscar");
        btnBuscarNombreEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreEliminarActionPerformed(evt);
            }
        });

        btnConfirmarEliminar.setText("Confirmar");
        btnConfirmarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnBuscarIdEliminar)
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarNombreEliminar)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEliminarPorID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(325, 325, 325))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)))
                        .addComponent(txtEliminarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelarEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btnConfirmarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEliminarPorID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEliminarPorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarIdEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarNombreEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelarEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEliminarPActionPerformed
        // TODO add your handling code here:
        im.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarEliminarPActionPerformed

    private void btnBuscarIdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdEliminarActionPerformed
        // TODO add your handling code here:
        int datoid = Integer.parseInt(txtEliminarPorID.getText());
        String resultadoid = null ; 
        for(i=0 ; i< Data.contador ; i++) {
            if(Data.IDpersonaje[i]== datoid){
                resultadoid = "¿DESEA ELIMINAR ESTE PERSONAJE?" + "\n"
                + "Nombre: " + Data.NombresPersonajes[i] + "\n"        
                + "ID: " + Data.IDpersonaje[i] + "\n"
                + "Arma: " + Data.NombresArmas[i] + "\n"
                + "Puntos de vida: " + Data.PuntosVida[i] + "\n"
                + "Ataque del personaje: " + Data.NivelAtaque[i] + "\n"
                + "Velocidad del personaje: " + Data.Velocidad[i] + "\n"
                + "Agilidad del personaje: " + Data.Agilidad[i] + "\n"
                + "Defensa del personaje: " + Data.Defensa[i] + "\n" ;
            }
            posicion = i ;
        }
        
        txtResultadoBEliminar.setText(resultadoid);
    }//GEN-LAST:event_btnBuscarIdEliminarActionPerformed

    private void btnBuscarNombreEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreEliminarActionPerformed
        // TODO add your handling code here:
        String datonombre = txtEliminarPorNombre.getText() ;
        String resultadonombre = null ;
        for(i=0 ; i<Data.contador ; i++){
            if(Data.NombresPersonajes[i] != null && Data.NombresPersonajes[i].equalsIgnoreCase(datonombre)){
                resultadonombre = "¿DESEA ELIMINAR ESTE PERSONAJE?" + "\n"
                + "Nombre: " + Data.NombresPersonajes[i] + "\n"       
                + "ID: " + Data.IDpersonaje[i] + "\n"
                + "Arma: " + Data.NombresArmas[i] + "\n"
                + "Puntos de vida: " + Data.PuntosVida[i] + "\n"
                + "Ataque del personaje: " + Data.NivelAtaque[i] + "\n"
                + "Velocidad del personaje: " + Data.Velocidad[i] + "\n"
                + "Agilidad del personaje: " + Data.Agilidad[i] + "\n"
                + "Defensa del personaje: " + Data.Defensa[i] + "\n" ;
            }
           posicion = i ; 
        }
    
        txtResultadoBEliminar.setText(resultadonombre);
    }//GEN-LAST:event_btnBuscarNombreEliminarActionPerformed

    private void btnConfirmarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEliminarActionPerformed
        // TODO add your handling code here:
       for(int j = posicion ; j < Data.contador - 1; j++){
           Data.NombresPersonajes[j] = Data.NombresPersonajes[j+1] ;
           Data.NombresArmas[j] = Data.NombresArmas[j+1] ;
           Data.PuntosVida[j] = Data.PuntosVida[j+1] ;
           Data.NivelAtaque[j] = Data.NivelAtaque[j+1] ;
           Data.Velocidad[j] = Data.Velocidad[j+1] ;
           Data.Agilidad[j] = Data.Agilidad[j+1] ;
           Data.Defensa[j] = Data.Defensa[j+1] ;
           Data.IDpersonaje[j] = Data.IDpersonaje[j+1] ;
        }
       
        Data.NombresPersonajes[Data.contador-1] = null ;
           Data.NombresArmas[Data.contador-1] = null ;
           Data.PuntosVida[Data.contador-1] = 0 ;
           Data.NivelAtaque[Data.contador -1] = 0 ;
           Data.Velocidad[Data.contador-1] = 0 ;
           Data.Agilidad[Data.contador-1] = 0 ;
           Data.Defensa[Data.contador-1] = 0;
           Data.IDpersonaje[Data.contador-1] =0;
           
           Data.contador-- ;
           Data.contadorId-- ;
           JOptionPane.showMessageDialog(this, "Personaje eliminado correctamente");
           
           im.setVisible(true) ;
           this.setVisible(false) ;
    }//GEN-LAST:event_btnConfirmarEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazEliminarPersonaje().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarIdEliminar;
    private javax.swing.JButton btnBuscarNombreEliminar;
    private javax.swing.JButton btnCancelarEliminarP;
    private javax.swing.JButton btnConfirmarEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEliminarPorID;
    private javax.swing.JTextField txtEliminarPorNombre;
    private javax.swing.JTextArea txtResultadoBEliminar;
    // End of variables declaration//GEN-END:variables
}
