/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica2;

import javax.swing.JOptionPane;

/**
 *
 * @author pc1
 */
public class InterfazModificarPersonaje extends javax.swing.JFrame {
    
    public int i ;
    public int posicion ;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazModificarPersonaje.class.getName());
    
    private InterfazMenu im ;
    
    
    /**
     * Creates new form InterfazModificarPersonaje
     */
    public InterfazModificarPersonaje() {
        initComponents();
    }
    
    public void setIm(InterfazMenu im2){
        this.im = im2 ;
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancelarMP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBuscarID = new javax.swing.JTextField();
        txtBuscarNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultadoB = new javax.swing.JTextArea();
        btnBid = new javax.swing.JButton();
        btnBuscarNombre = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtArmaMod = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHPMod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAtaqueMod = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtVelocidadMod = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAgilidadMod = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDefensaMod = new javax.swing.JTextField();
        btnModPersonaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("              MODIFICAR PERSONAJE ");

        btnCancelarMP.setText("Cancelar");
        btnCancelarMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMPActionPerformed(evt);
            }
        });

        jLabel2.setText("         BUSCAR POR ID");

        jLabel3.setText("     BUCAR POR NOMBRE");

        txtBuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarIDActionPerformed(evt);
            }
        });

        txtResultadoB.setColumns(20);
        txtResultadoB.setRows(5);
        jScrollPane1.setViewportView(txtResultadoB);

        btnBid.setText("Buscar");
        btnBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBidActionPerformed(evt);
            }
        });

        btnBuscarNombre.setText("Buscar");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("         DATOS A MODIFICAR");

        jLabel5.setText("Arma:");

        jLabel6.setText("Puntos de vida:");

        jLabel7.setText("Ataque:");

        jLabel8.setText("Velocidad:");

        jLabel9.setText("Agilidad:");

        jLabel10.setText("Defensa:");

        btnModPersonaje.setText("Guardar Cambios");
        btnModPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPersonajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBid)
                    .addComponent(txtBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(244, 244, 244)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtArmaMod)
                            .addComponent(txtHPMod)
                            .addComponent(txtAtaqueMod)
                            .addComponent(txtVelocidadMod)
                            .addComponent(txtAgilidadMod)
                            .addComponent(txtDefensaMod, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(btnCancelarMP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnModPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(79, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnBid))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArmaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHPMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAtaqueMod, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelocidadMod, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgilidadMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDefensaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarMP, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnModPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMPActionPerformed
        // TODO add your handling code here:
        im.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_btnCancelarMPActionPerformed

    private void txtBuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarIDActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtBuscarIDActionPerformed

    private void btnBidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBidActionPerformed
        // TODO add your handling code here:
        int datoid = Integer.parseInt(txtBuscarID.getText());
        String resultadoid = null ; 
        for(i=0 ; i< Data.contador ; i++) {
            if(Data.IDpersonaje[i]== datoid){
                resultadoid = "PERSONAJE A MODIFICAR"
                + "Nombre: " + Data.NombresPersonajes[i] + "\n"        
                + "ID: " + Data.IDpersonaje[i] + "\n"
                + "Arma: " + Data.NombresArmas[i] + "\n"
                + "Puntos de vida: " + Data.PuntosVida[i] + "\n"
                + "Ataque del personaje: " + Data.NivelAtaque[i] + "\n"
                + "Velocidad del personaje: " + Data.Velocidad[i] + "\n"
                + "Agilidad del personaje: " + Data.Agilidad[i] + "\n"
                + "Defensa del personaje: " + Data.Defensa[i] + "\n" ;
            }
            posicion = i ;
        }
        
        txtResultadoB.setText(resultadoid);
    }//GEN-LAST:event_btnBidActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        // TODO add your handling code here:
        String datonombre = txtBuscarNombre.getText() ;
        String resultadonombre = null ;
        for(i=0 ; i<Data.contador ; i++){
            if(Data.NombresPersonajes[i] != null && Data.NombresPersonajes[i].equalsIgnoreCase(datonombre)){
                resultadonombre = "PERSONAJE A MODIFICAR"
                + "Nombre: " + Data.NombresPersonajes[i] + "\n"       
                + "ID: " + Data.IDpersonaje[i] + "\n"
                + "Arma: " + Data.NombresArmas[i] + "\n"
                + "Puntos de vida: " + Data.PuntosVida[i] + "\n"
                + "Ataque del personaje: " + Data.NivelAtaque[i] + "\n"
                + "Velocidad del personaje: " + Data.Velocidad[i] + "\n"
                + "Agilidad del personaje: " + Data.Agilidad[i] + "\n"
                + "Defensa del personaje: " + Data.Defensa[i] + "\n" ;
            }
           posicion = i ; 
        }
    
        txtResultadoB.setText(resultadonombre);
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnModPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPersonajeActionPerformed
        // TODO add your handling code here:
    String armamod = txtArmaMod.getText() ;
    if(!armamod.isEmpty()){
    Data.NombresArmas[posicion] = armamod ;
    }

    try{
    int hpmod = Integer.parseInt(txtHPMod.getText());
        if (hpmod>=100&&hpmod<=500){
            Data.PuntosVida[posicion] = hpmod ;
        } else {
    JOptionPane.showMessageDialog(this, "Puntos de vida del personaje debe estar entre 100 y 500");
    return;
          }
    }catch(NumberFormatException e) {
    }
    
    try{
    int nivelAtaquemod = Integer.parseInt(txtAtaqueMod.getText());    
        if (nivelAtaquemod>=10 && nivelAtaquemod<=100){
            Data.NivelAtaque[posicion] = nivelAtaquemod ;
        } else {
    JOptionPane.showMessageDialog(this, "Nivel de ataque del personaje debe estar entre 10 y 100");
    return;
    }
    }catch(NumberFormatException e){
    }
    
    try{
    int velocidadmod = Integer.parseInt(txtVelocidadMod.getText());   
        if (velocidadmod>=1 && velocidadmod<=10){
            Data.Velocidad[posicion] = velocidadmod ;
        } else {
    JOptionPane.showMessageDialog(this, "Velocidad del personaje debe estar entre 1 y 10");
    return;
    }
    }catch(NumberFormatException e) {
    }
    
    try{
    int agilidadmod = Integer.parseInt(txtAgilidadMod.getText());
        if (agilidadmod>=1 && agilidadmod<=10){
            Data.Agilidad[posicion] = agilidadmod ;
        } else {
    JOptionPane.showMessageDialog(this, "Agilidad del personaje debe estar entre 1 y 10");
    return;
    }
    }catch(NumberFormatException e){
    }
    
    try{
    int defensamod = Integer.parseInt(txtDefensaMod.getText());    
        if (defensamod>=1 && defensamod<=50){
            Data.Defensa[posicion] = defensamod ;
        } else {
    JOptionPane.showMessageDialog(this, "Defensa del personaje debe estar entre 1 y 10");
    return;
    }
    }catch(NumberFormatException e){
    }

    JOptionPane.showMessageDialog(this, "Personaje modificado correctamente");
    
        im.setVisible(true) ;
        this.setVisible(false) ;
        
        
    }//GEN-LAST:event_btnModPersonajeActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazModificarPersonaje().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBid;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnCancelarMP;
    private javax.swing.JButton btnModPersonaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAgilidadMod;
    private javax.swing.JTextField txtArmaMod;
    private javax.swing.JTextField txtAtaqueMod;
    private javax.swing.JTextField txtBuscarID;
    private javax.swing.JTextField txtBuscarNombre;
    private javax.swing.JTextField txtDefensaMod;
    private javax.swing.JTextField txtHPMod;
    private javax.swing.JTextArea txtResultadoB;
    private javax.swing.JTextField txtVelocidadMod;
    // End of variables declaration//GEN-END:variables
}
