/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica2;

import javax.swing.JOptionPane;

/**
 *
 * @author pc1
 */
public class InterfazAgregarPersonaje extends javax.swing.JFrame {
    
    
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazAgregarPersonaje.class.getName());

    private InterfazMenu im ; 
    
    
    
    /**
     * Creates new form InterfazAgregarPersonaje
     */
    public InterfazAgregarPersonaje() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        btnCancelarAP = new javax.swing.JButton();
        btnAgregarP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        txtArmaP = new javax.swing.JTextField();
        txtPuntosVidaP = new javax.swing.JTextField();
        txtNivelAtaqueP = new javax.swing.JTextField();
        txtVelocidadP = new javax.swing.JTextField();
        txtAgilidadP = new javax.swing.JTextField();
        txtDefensaP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("          AGREGAR PERSONAJE");

        btnCancelarAP.setText("Cancelar");
        btnCancelarAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAPActionPerformed(evt);
            }
        });

        btnAgregarP.setText("Agregar Personaje");
        btnAgregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Arma: ");

        jLabel4.setText("  Punto de vida:");

        jLabel5.setText("Nivel de ataque:");

        jLabel6.setText("Velocidad:");

        jLabel7.setText("  Agilidad:");

        jLabel8.setText("  Defensa:");

        txtNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePActionPerformed(evt);
            }
        });

        txtArmaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArmaPActionPerformed(evt);
            }
        });

        txtPuntosVidaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntosVidaPActionPerformed(evt);
            }
        });

        txtNivelAtaqueP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelAtaquePActionPerformed(evt);
            }
        });

        txtVelocidadP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVelocidadPActionPerformed(evt);
            }
        });

        txtAgilidadP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgilidadPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnCancelarAP, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 149, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreP)
                            .addComponent(txtPuntosVidaP)
                            .addComponent(txtArmaP)
                            .addComponent(txtNivelAtaqueP)
                            .addComponent(txtVelocidadP)
                            .addComponent(txtAgilidadP)
                            .addComponent(txtDefensaP, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArmaP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPuntosVidaP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtNivelAtaqueP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVelocidadP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAgilidadP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDefensaP, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarAP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setIm(InterfazMenu im1){
        this.im = im1 ;
    
    }
    
    
    private void btnCancelarAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAPActionPerformed
        // TODO add your handling code here:
        im.setVisible(true) ;
        this.setVisible(false) ;
        
    }//GEN-LAST:event_btnCancelarAPActionPerformed

    private void txtNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePActionPerformed

    private void txtArmaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArmaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArmaPActionPerformed

    private void txtPuntosVidaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntosVidaPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntosVidaPActionPerformed

    private void txtNivelAtaquePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelAtaquePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelAtaquePActionPerformed

    private void txtVelocidadPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVelocidadPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVelocidadPActionPerformed

    private void txtAgilidadPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgilidadPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgilidadPActionPerformed

    private void btnAgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPActionPerformed
        String nombre = txtNombreP.getText();
    String arma = txtArmaP.getText();
    int hp = Integer.parseInt(txtPuntosVidaP.getText());
    int nivelAtaque = Integer.parseInt(txtNivelAtaqueP.getText());
    int velocidad = Integer.parseInt(txtVelocidadP.getText());
    int agilidad = Integer.parseInt(txtAgilidadP.getText());
    int defensa = Integer.parseInt(txtDefensaP.getText());
   
    for (int i = 0; i < Data.contador; i++) {
        if (Data.NombresPersonajes[i] != null && Data.NombresPersonajes[i].equalsIgnoreCase(nombre)) {
            JOptionPane.showMessageDialog(this, "NOMBRE EN USO");
            return;
        }
    }
    
    Data.NombresPersonajes[Data.contador] = nombre;
    Data.NombresArmas[Data.contador] = arma ;
    
    if (hp>=100&&hp<=500){
        Data.PuntosVida[Data.contador] = hp ;
    } else {
    JOptionPane.showMessageDialog(this, "Puntos de vida del personaje debe estar entre 100 y 500");
    return;
    }
    
    if (nivelAtaque>=10 && nivelAtaque<=100){
        Data.NivelAtaque[Data.contador] = nivelAtaque ;
    } else {
    JOptionPane.showMessageDialog(this, "Nivel de ataque del personaje debe estar entre 10 y 100");
    return;
    }
    
    if (velocidad>=1 && velocidad<=10){
        Data.Velocidad[Data.contador] = velocidad ;
    } else {
    JOptionPane.showMessageDialog(this, "Velocidad del personaje debe estar entre 1 y 10");
    return;
    }
    
    if (agilidad>=1 && agilidad<=10){
        Data.Agilidad[Data.contador] = agilidad ;
    } else {
    JOptionPane.showMessageDialog(this, "Agilidad del personaje debe estar entre 1 y 10");
    return;
    }
    
    if (defensa>=1 && defensa<=50){
        Data.Defensa[Data.contador] = defensa ;
    } else {
    JOptionPane.showMessageDialog(this, "Defensa del personaje debe estar entre 1 y 10");
    return;
    }
 
    Data.IDpersonaje[Data.contador] = Data.contadorId ;
    JOptionPane.showMessageDialog(this, "ID del personaje es: " + Data.IDpersonaje[Data.contador]);
    Data.contador++ ;
    Data.contadorId++ ;
    
    JOptionPane.showMessageDialog(this, "Personaje agregado correctamente");
    
    
// salir del método
im.setVisible(true) ;
        this.setVisible(false) ;
    }//GEN-LAST:event_btnAgregarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazAgregarPersonaje().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarP;
    private javax.swing.JButton btnCancelarAP;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAgilidadP;
    private javax.swing.JTextField txtArmaP;
    private javax.swing.JTextField txtDefensaP;
    private javax.swing.JTextField txtNivelAtaqueP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtPuntosVidaP;
    private javax.swing.JTextField txtVelocidadP;
    // End of variables declaration//GEN-END:variables
}
